package com.requests;

import com.database.model.User;
import com.database.repositories.UserRepository;
import com.models.CallRequest;
import com.models.CallResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class RequestController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @RequestMapping(value="/ebank", method = RequestMethod.POST)
    public CallResponse RequestDispatcher(@RequestBody CallRequest request){
        if(request.getMethod() == null){
            return new CallResponse(404, new Object[]{"Invalid CallRequest"});
        }

        User n = new User();
        n.setFirstName(request.getParams()[0].toString());
        n.setEmail(request.getParams()[1].toString());
        userRepository.save(n);

        n = userRepository.findById(1);
        n.setEmail("qjwejlqkwjelqkjwelkqjw");
        userRepository.save(n);

        return new CallResponse(1, new Object []{"fuck " + request.getId()});
    }
}
